### ISSUE TITLE
魅族18 安卓13 多开应用没有网络

### ISSUE THREAD

**Issue by zhengxingjian** [ServenScorpion/VirtualApp#51]

**Comment by ServenScorpion** [comment]
啥应用？


zhengxingjian ***@***.***> 于2023年10月9日周一 17:27写道：

**Comment by zhengxingjian** [comment]
换了小米5x 4G很早的机型可以，魅族18是所有的应用都没有网络(微信，快手，UC浏览器等都上不了网），单机应用到是正常运行，再发现个问题是，添加桌面快捷方式点击无效。

**Comment by zhengxingjian** [comment]
error creating cache file /data/user_de/0/com.carlos.multiapp.ext/code_cache/com.android.opengl.shaders_cache: No such file or directory (2)
2023-10-10 09:17:15.074 22499-22499 ShadowJobService        com.carlos.multiapp                  E  -> onCreate
2023-10-10 09:17:15.076 22499-22499 ShadowJobService        com.carlos.multiapp                  E  -> onBind: Intent { meizuflg=0x400000 cmp=com.carlos.multiapp/com.lody.virtual.client.stub.ShadowJobService }
2023-10-10 09:17:15.095 22499-22499 ShadowJobWorkService    com.carlos.multiapp                  I  ShadowJobService:binService:ComponentInfo{com.smile.gifmaker/androidx.work.impl.background.systemjob.SystemJobService}, jobId=10
2023-10-10 09:17:15.099 22499-22499 ShadowJobWorkService    com.carlos.multiapp                  E  java.lang.SecurityException: Not allowed to bind to service Intent { cmp=com.smile.gifmaker/androidx.work.impl.background.systemjob.SystemJobService (has extras) }
                                                                                                    	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:2048)
                                                                                                    	at android.app.ContextImpl.bindService(ContextImpl.java:1959)
                                                                                                    	at android.content.ContextWrapper.bindService(ContextWrapper.java:853)
                                                                                                    	at com.lody.virtual.client.ipc.VActivityManager.bindService(VActivityManager.java:575)

**Comment by zhengxingjian** [comment]
这里是要去getPackageInfo：com.carlos.multiapp.ext   service:com.lody.virtual.server.interfaces.IPackageManager$Stub$Proxy@5288e8b
2023-10-10 14:39:17.170  1618-1904  BatteryStatsImpl        system_server                        E  Unable to find object for com.carlos.multiapp/com.lody.virtual.client.stub.ShadowJobService in uid 10036 mapsize=0 activeoverflow=null curoverflow=null lastCleanupTime=-2h43m42s416ms
2023-10-10 14:39:17.173  1618-1904  BatteryStatsImpl        system_server                        E  Unable to find object for com.carlos.multiapp/com.lody.virtual.client.stub.ShadowJobService in uid 10036 mapsize=0 activeoverflow=null curoverflow=null lastCleanupTime=-2h43m42s420ms
2023-10-10 14:39:17.178  1618-1904  BatteryStatsImpl        system_server                        E  Unable to find object for com.carlos.multiapp/com.lody.virtual.client.stub.ShadowJobService in uid 10036 mapsize=0 activeoverflow=null curoverflow=null lastCleanupTime=-2h43m42s424ms
2023-10-10 14:39:17.181  1618-1904  BatteryStatsImpl        system_server                        E  Unable to find object for com.carlos.multiapp/com.lody.virtual.client.stub.ShadowJobService in uid 10036 mapsize=0 activeoverflow=null curoverflow=null lastCleanupTime=-2h43m42s428ms
2023-10-10 14:39:17.183  1618-1904  BatteryStatsImpl        system_server                        E  Unable to find object for com.carlos.multiapp/com.lody.virtual.client.stub.ShadowJobService in uid 10036 mapsize=0 activeoverflow=null curoverflow=null lastCleanupTime=-2h43m42s430ms
2023-10-10 14:39:17.185  1618-1904  BatteryStatsImpl        system_server                        E  Unable to find object for com.carlos.multiapp/com.lody.virtual.client.stub.ShadowJobService in uid 10036 mapsize=0 activeoverflow=null curoverflow=null lastCleanupTime=-2h43m42s432ms
2023-10-10 14:39:17.186  1618-1618  JobSchedul...oncurrency system_server                        E  Error executing JobStatus{3207373 #u0a36/23 com.carlos.multiapp/com.lody.virtual.client.stub.ShadowJobService u=0 s=10036 TIME=-7s477ms:none NET STORENOTLOW READY}
2023-10-10 14:39:17.186  1618-1618  JobSchedul...oncurrency system_server                        E  Error executing JobStatus{3207373 #u0a36/23 com.carlos.multiapp/com.lody.virtual.client.stub.ShadowJobService u=0 s=10036 TIME=-7s478ms:none NET STORENOTLOW READY}
2023-10-10 14:39:17.186  1618-1618  JobSchedul...oncurrency system_server                        E  Error executing JobStatus{3207373 #u0a36/23 com.carlos.multiapp/com.lody.virtual.client.stub.ShadowJobService u=0 s=10036 TIME=-7s478ms:none NET STORENOTLOW READY}
2023-10-10 14:39:17.186  1618-1618  JobSchedul...oncurrency system_server                        E  Error executing JobStatus{3207373 #u0a36/23 com.carlos.multiapp/com.lody.virtual.client.stub.ShadowJobService u=0 s=10036 TIME=-7s478ms:none NET STORENOTLOW READY}
2023-10-10 14:39:17.187  1618-1618  JobSchedul...oncurrency system_server                        E  Error executing JobStatus{3207373 #u0a36/23 com.carlos.multiapp/com.lody.virtual.client.stub.ShadowJobService u=0 s=10036 TIME=-7s478ms:none NET STORENOTLOW READY}
2023-10-10 14:39:17.187  1618-1618  JobSchedul...oncurrency system_server                        E  Error executing JobStatus{3207373 #u0a36/23 com.carlos.multiapp/com.lody.virtual.client.stub.ShadowJobService u=0 s=10036 TIME=-7s479ms:none NET STORENOTLOW READY}
2023-10-10 14:39:17.194  1618-1904  BatteryStatsImpl        system_server                        E  Unable to find object for com.carlos.multiapp/com.lody.virtual.client.stub.ShadowJobService in uid 10036 mapsize=0 activeoverflow=null curoverflow=null lastCleanupTime=-2h43m42s439ms
2023-10-10 14:39:17.194  1618-1904  BatteryStatsImpl        system_server                        E  Unable to find object for com.carlos.multiapp/com.lody.virtual.client.stub.ShadowJobService in uid 10036 mapsize=0 activeoverflow=null curoverflow=null lastCleanupTime=-2h43m42s440ms
2023-10-10 14:39:17.194  1618-1904  BatteryStatsImpl        system_server                        E  Unable to find object for com.carlos.multiapp/com.lody.virtual.client.stub.ShadowJobService in uid 10036 mapsize=0 activeoverflow=null curoverflow=null lastCleanupTime=-2h43m42s441ms
2023-10-10 14:39:17.195  1618-1904  BatteryStatsImpl        system_server                        E  Unable to find object for com.carlos.multiapp/com.lody.virtual.client.stub.ShadowJobService in uid 10036 mapsize=0 activeoverflow=null curoverflow=null lastCleanupTime=-2h43m42s441ms
2023-10-10 14:39:17.195  1618-1904  BatteryStatsImpl        system_server                        E  Unable to find object for com.carlos.multiapp/com.lody.virtual.client.stub.ShadowJobService in uid 10036 mapsize=0 activeoverflow=null curoverflow=null lastCleanupTime=-2h43m42s442ms
2023-10-10 14:39:17.196  1618-1904  BatteryStatsImpl        system_server                        E  Unable to find object for com.carlos.multiapp/com.lody.virtual.client.stub.ShadowJobService in uid 10036 mapsize=0 activeoverflow=null curoverflow=null lastCleanupTime=-2h43m42s443ms
2023-10-10 14:39:17.196  1618-1618  JobSchedul...oncurrency system_server                        E  Error executing JobStatus{384d3cf #u0a36/24 com.carlos.multiapp/com.lody.virtual.client.stub.ShadowJobService u=0 s=10036 TIME=-7s125ms:none READY}
2023-10-10 14:39:17.196  1618-1618  JobSchedul...oncurrency system_server                        E  Error executing JobStatus{384d3cf #u0a36/24 com.carlos.multiapp/com.lody.virtual.client.stub.ShadowJobService u=0 s=10036 TIME=-7s125ms:none READY}
2023-10-10 14:39:17.196  1618-1618  JobSchedul...oncurrency system_server                        E  Error executing JobStatus{384d3cf #u0a36/24 com.carlos.multiapp/com.lody.virtual.client.stub.ShadowJobService u=0 s=10036 TIME=-7s125ms:none READY}
2023-10-10 14:39:17.196  1618-1618  JobSchedul...oncurrency system_server                        E  Error executing JobStatus{384d3cf #u0a36/24 com.carlos.multiapp/com.lody.virtual.client.stub.ShadowJobService u=0 s=10036 TIME=-7s125ms:none READY}
2023-10-10 14:39:17.196  1618-1618  JobSchedul...oncurrency system_server                        E  Error executing JobStatus{384d3cf #u0a36/24 com.carlos.multiapp/com.lody.virtual.client.stub.ShadowJobService u=0 s=10036 TIME=-7s125ms:none READY}
2023-10-10 14:39:17.196  1618-1618  JobSchedul...oncurrency system_server                        E  Error executing JobStatus{384d3cf #u0a36/24 com.carlos.multiapp/com.lody.virtual.client.stub.ShadowJobService u=0 s=10036 TIME=-7s125ms:none READY}
