### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by HappyFatDoge** [ServenScorpion/VirtualApp#60]
拉取项目代码直接运行，无法跑起来，是有什么其他配置吗

**Comment by ServenScorpion** [comment]
你如果按完整项目clone 去没有问题的才对，没有其他配置哈、无法跑起来有log 还是 什么情况么？ 注意gradle 版本别太低就行

FatDoge ***@***.***> 于2024年11月4日周一 16:24写道：

**Comment by HappyFatDoge** [comment]
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.carlos.common.App" on path: DexPathList[[zip file "/data/app/~~AiEpeFPPHp3kYAcCDEVcoA==/com.carlos.multiapp-E3zqGXZtYhImK1G9Mp1SQA==/base.apk"],nativeLibraryDirectories=[/data/app/~~AiEpeFPPHp3kYAcCDEVcoA==/com.carlos.multiapp-E3zqGXZtYhImK1G9Mp1SQA==/lib/arm64, /data/app/~~AiEpeFPPHp3kYAcCDEVcoA==/com.carlos.multiapp-E3zqGXZtYhImK1G9Mp1SQA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
                                                                                                    	at android.app.Instrumentation.newApplication(Instrumentation.java:1254)
                                                                                                    	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1485)
                                                                                                    	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1422) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7289) 
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:211) 
                                                                                                    	at android.os.Looper.loop(Looper.java:300) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8503) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954) 
                                                                                                    	Suppressed: java.io.IOException: Failed to open dex files from /data/app/~~AiEpeFPPHp3kYAcCDEVcoA==/com.carlos.multiapp-E3zqGXZtYhImK1G9Mp1SQA==/base.apk because: Dex file '/data/app/~~AiEpeFPPHp3kYAcCDEVcoA==/com.carlos.multiapp-E3zqGXZtYhImK1G9Mp1SQA==/base.apk' has zero length
                                                                                                    		at dalvik.system.DexFile.openDexFileNative(Native Method)
                                                                                                    		at dalvik.system.DexFile.openDexFile(DexFile.java:371)
                                                                                                    		at dalvik.system.DexFile.<init>(DexFile.java:113)
                                                                                                    		at dalvik.system.DexFile.<init>(DexFile.java:86)
                                                                                                    		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:438)
                                                                                                    		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:397)
                                                                                                    		at dalvik.system.DexPathList.<init>(DexPathList.java:166)
                                                                                                    		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:160)
                                                                                                    		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:130)
                                                                                                    		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:146)
                                                                                                    		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:93)
                                                                                                    		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:134)
                                                                                                    		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:126)
                                                                                                    		at android.app.ApplicationLoaders.getClassLoaderWithSharedLibraries(ApplicationLoaders.java:61)
                                                                                                    		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:1047)
                                                                                                    		at android.app.LoadedApk.getClassLoader(LoadedApk.java:1139)
                                                                                                    		at android.app.LoadedApk.getResources(LoadedApk.java:1398)
                                                                                                    		at android.app.ContextImpl.createAppContext(ContextImpl.java:3100)
                                                                                                    		at android.app.ContextImpl.createAppContext(ContextImpl.java:3092)


正常clone，运行后报错

**Comment by ServenScorpion** [comment]
你确定你自己的修改或者环境吧、肯定没问题的

FatDoge ***@***.***> 于2024年11月5日周二 10:12写道：

**Comment by HappyFatDoge** [comment]
我拉取之后直接运行的，没有修改，我再看看吧
